name: CI - Blacksmith

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: blacksmith-2vcpu-ubuntu-2404

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install
        run: npm ci

      - name: Type checking
        run: npm run typecheck

      - name: Linting
        run: npm run lint:fix

      - name: Run tests
        run: npm run test:once

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
